// Code generated by wireinjectgen; DO NOT EDIT.
package wire

import (
	"github.com/google/wire"
	services "audio-book-ai/src/core/application/services"
	authusecases "audio-book-ai/src/core/application/usecases/authusecases"
	bookusecases "audio-book-ai/src/core/application/usecases/bookusecases"
	asynctask "audio-book-ai/src/entrypoint/asynctask"
	book "audio-book-ai/src/entrypoint/asynctask/handlers/book"
	http "audio-book-ai/src/entrypoint/http"
	groups "audio-book-ai/src/entrypoint/http/groups"
	auth "audio-book-ai/src/entrypoint/http/handlers/auth"
	book2 "audio-book-ai/src/entrypoint/http/handlers/book"
	middlewares "audio-book-ai/src/entrypoint/http/interceptor/middlewares"
	asynqtask "audio-book-ai/src/infrastructure/asynqtask"
	audio "audio-book-ai/src/infrastructure/audio"
	chunk "audio-book-ai/src/infrastructure/chunk"
	db "audio-book-ai/src/infrastructure/db"
	echohttp "audio-book-ai/src/infrastructure/echohttp"
	context "audio-book-ai/src/infrastructure/echohttp/context"
	env "audio-book-ai/src/infrastructure/env"
	gateway "audio-book-ai/src/infrastructure/gateway"
	ingest "audio-book-ai/src/infrastructure/ingest"
	logger "audio-book-ai/src/infrastructure/logger"
	repository "audio-book-ai/src/infrastructure/persistence/repository"
	security "audio-book-ai/src/infrastructure/security"
	storage "audio-book-ai/src/infrastructure/storage"
	tts "audio-book-ai/src/infrastructure/tts"
)

var ProviderSet = wire.NewSet(
	services.NewUserAuthTokenService,
	authusecases.NewGoogleLoginUseCase,
	authusecases.NewRefreshTokenUseCase,
	bookusecases.NewBookCreateUseCase,
	bookusecases.NewBookGetUseCase,
	bookusecases.NewProcessBookUseCase,
	asynctask.NewApp,
	book.NewProcessHandler,
	http.NewApp,
	groups.NewAuthGroup,
	groups.NewBookGroup,
	auth.NewGoogleLoginHandler,
	auth.NewMeHandler,
	auth.NewRefreshTokenHandler,
	book2.NewAudioHandler,
	book2.NewCreateHandler,
	book2.NewGetHandler,
	middlewares.NewJwtAuthMiddleware,
	asynqtask.NewAsynqClient,
	asynqtask.NewEnqueuer,
	audio.NewWAVConcatenator,
	chunk.NewParagraphChunker,
	db.NewDatabase,
	db.NewGormDB,
	echohttp.NewServerImpl,
	context.NewEchoContext,
	env.NewEnv,
	gateway.NewGoogleOAuthGatewayImpl,
	ingest.NewTxtExtractor,
	logger.NewDailyZapLogger,
	repository.NewBaseRepository,
	repository.NewBookRepositoryImpl,
	repository.NewUserRepositoryImpl,
	security.NewJwtTokenService,
	storage.NewFileStore,
	tts.NewMockProvider,
)
