docker-run.dev:
	docker compose -f docker-compose.dev.yml --env-file ../env/.env.local up --build -d

docker-down.dev:
	docker compose -f docker-compose.dev.yml down

docker-logs.dev:
	docker compose -f docker-compose.dev.yml logs -f
