// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"audio-book-ai/src/core/application/services"
	"audio-book-ai/src/core/application/usecases/authusecases"
	"audio-book-ai/src/core/application/usecases/bookusecases"
	"audio-book-ai/src/entrypoint/asynctask"
	book2 "audio-book-ai/src/entrypoint/asynctask/handlers/book"
	"audio-book-ai/src/entrypoint/http"
	"audio-book-ai/src/entrypoint/http/groups"
	"audio-book-ai/src/entrypoint/http/handlers/auth"
	"audio-book-ai/src/entrypoint/http/handlers/book"
	"audio-book-ai/src/entrypoint/http/interceptor/middlewares"
	"audio-book-ai/src/infrastructure/asynqtask"
	"audio-book-ai/src/infrastructure/audio"
	"audio-book-ai/src/infrastructure/chunk"
	"audio-book-ai/src/infrastructure/db"
	"audio-book-ai/src/infrastructure/echohttp"
	"audio-book-ai/src/infrastructure/env"
	"audio-book-ai/src/infrastructure/gateway"
	"audio-book-ai/src/infrastructure/ingest"
	"audio-book-ai/src/infrastructure/logger"
	"audio-book-ai/src/infrastructure/persistence/repository"
	"audio-book-ai/src/infrastructure/security"
	"audio-book-ai/src/infrastructure/storage"
	"audio-book-ai/src/infrastructure/tts"
)

// Injectors from wire.go:

func InitHttpApp() *http.App {
	httpServer := echohttp.NewServerImpl()
	envEnv := env.NewEnv()
	zapLogger := logger.NewDailyZapLogger()
	gormDB := db.NewGormDB(envEnv, zapLogger)
	database := db.NewDatabase(gormDB)
	baseRepository := repository.NewBaseRepository(database)
	bookRepository := repository.NewBookRepositoryImpl(baseRepository)
	store := storage.NewFileStore(envEnv)
	client := asynqtask.NewAsynqClient(envEnv)
	enqueuer := asynqtask.NewEnqueuer(client)
	bookCreateUseCase := bookusecases.NewBookCreateUseCase(bookRepository, store, enqueuer)
	createHandler := book.NewCreateHandler(bookCreateUseCase)
	bookGetUseCase := bookusecases.NewBookGetUseCase(bookRepository)
	getHandler := book.NewGetHandler(bookGetUseCase)
	audioHandler := book.NewAudioHandler(bookGetUseCase)
	bookGroup := groups.NewBookGroup(createHandler, getHandler, audioHandler)
	googleOAuthGateway := gateway.NewGoogleOAuthGatewayImpl(envEnv)
	userRepository := repository.NewUserRepositoryImpl(baseRepository)
	tokenServicePort := security.NewJwtTokenService(envEnv)
	userAuthTokenService := services.NewUserAuthTokenService(tokenServicePort, userRepository, envEnv)
	googleLoginUseCase := authusecases.NewGoogleLoginUseCase(googleOAuthGateway, userRepository, userAuthTokenService)
	googleLoginHandler := auth.NewGoogleLoginHandler(googleLoginUseCase)
	refreshTokenUseCase := authusecases.NewRefreshTokenUseCase(userAuthTokenService)
	refreshTokenHandler := auth.NewRefreshTokenHandler(refreshTokenUseCase)
	meHandler := auth.NewMeHandler()
	authGroup := groups.NewAuthGroup(googleLoginHandler, refreshTokenHandler, meHandler)
	jwtAuthMiddleware := middlewares.NewJwtAuthMiddleware(userAuthTokenService)
	app := http.NewApp(httpServer, bookGroup, authGroup, jwtAuthMiddleware, envEnv)
	return app
}

func InitAsyncApp() *asynctask.App {
	envEnv := env.NewEnv()
	zapLogger := logger.NewDailyZapLogger()
	gormDB := db.NewGormDB(envEnv, zapLogger)
	database := db.NewDatabase(gormDB)
	baseRepository := repository.NewBaseRepository(database)
	bookRepository := repository.NewBookRepositoryImpl(baseRepository)
	store := storage.NewFileStore(envEnv)
	extractor := ingest.NewTxtExtractor()
	chunker := chunk.NewParagraphChunker()
	ttsProvider := tts.NewMockProvider()
	concatenator := audio.NewWAVConcatenator()
	processBookUseCase := bookusecases.NewProcessBookUseCase(bookRepository, store, extractor, chunker, ttsProvider, concatenator)
	processHandler := book2.NewProcessHandler(processBookUseCase)
	app := asynctask.NewApp(envEnv, processHandler)
	return app
}
